# Generated by Django 6.0.7 on 2026-07-14 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('purok_zone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('evacuated', 'Evacuated')], default='active', max_length=20)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'db_table': 'residents',
                'ordering': ['purok_zone', 'full_name'],
                'indexes': [models.Index(fields=['mobile_number'], name='residents_mobile__740383_idx'), models.Index(fields=['purok_zone'], name='residents_purok_z_21d203_idx'), models.Index(fields=['status'], name='residents_status_83dd54_idx'), models.Index(fields=['sms_enabled'], name='residents_sms_ena_f956d4_idx')],
            },
        ),
    ]
