# Generated by Django 6.0.7 on 2026-07-14 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('water_level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodAlert',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_level', models.CharField(choices=[('Alert', 'Alert'), ('Warning', 'Warning'), ('Danger', 'Danger')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='water_level.waterlevelreading')),
            ],
            options={
                'verbose_name': 'Flood Alert',
                'verbose_name_plural': 'Flood Alerts',
                'db_table': 'flood_alerts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='flood_alert_timesta_a02d6a_idx'), models.Index(fields=['alert_level'], name='flood_alert_alert_l_c57828_idx'), models.Index(fields=['is_active'], name='flood_alert_is_acti_5b757c_idx'), models.Index(fields=['reading'], name='flood_alert_reading_757a98_idx')],
            },
        ),
    ]
