# Generated by Django 6.0.7 on 2026-07-14 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevelReading',
            fields=[
                ('reading_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('water_level_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Alert', 'Alert'), ('Warning', 'Warning'), ('Danger', 'Danger')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('sensor_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='online', max_length=20)),
                ('gsm_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', max_length=20)),
                ('firebase_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Water Level Reading',
                'verbose_name_plural': 'Water Level Readings',
                'db_table': 'water_level_readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='water_level_timesta_ae2727_idx'), models.Index(fields=['status'], name='water_level_status_a6751e_idx'), models.Index(fields=['-timestamp'], name='water_level_timesta_f261ec_idx')],
            },
        ),
    ]
