# Generated by Django 6.0.7 on 2026-07-14 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('sms_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='alerts.floodalert')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='residents.resident')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'db_table': 'sms_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sent_at'], name='sms_logs_sent_at_7a518b_idx'), models.Index(fields=['delivery_status'], name='sms_logs_deliver_fe28ca_idx'), models.Index(fields=['resident'], name='sms_logs_residen_d8705f_idx'), models.Index(fields=['alert'], name='sms_logs_alert_i_6a519a_idx')],
            },
        ),
    ]
